minimal_translation_percent = 1

cache_path = "cache.json"
output_path = "diagrams/dwarf-fortress-steam.svg"
input_path = "translations-backup/translations/dwarf-fortress-steam/"

[diagram]
width = 600
line_height = 14

[notranslate_tagged_strings]
hardcoded_steam = 906
